id: IDD6E3CAF
ocr_import_info:
  timestamp: '2023-08-15T02:12:35.544948+00:00'
  batch_id: batch-ac2c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-15 03:12:53.604700+00:00
last_modified: 2023-08-15 03:12:53.604708+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3643
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3643
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་ངེས་ཀྱི་འགྲེལ་ཆེན་ལས་མཚན་དོན་ཟུར་དུ་བཀོལ་བ་སོགས་ཆོས་ཚན་ཁག་ཅིག
  languages:
  - bo
  author: བུ་སྟོན་རིན་ཆེན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.954260765474607
  ocr_word_median_confidence_index: 0.9929071
bases:
  I1KG3651:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3651
      total_pages: 1068
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3651.txt
    statistics:
      ocr_word_median_confidence_index: 0.9929071
      ocr_word_mean_confidence_index: 0.954260765474607
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
